variavel = input("Digite alguma coisa: ")
print("O tipo primitivo desse valor é: ", type(variavel))
print('Possui espaços: ', variavel.isspace())
print("São numeros: ", variavel.isnumeric())
print("São letras: ", variavel.isalpha())
print("São alfanuméricos: ", variavel.isalnum())
print("São maiusculas: ", variavel.isupper())
print("São minusculas: ", variavel.islower())
print("São capitalizadas: ", variavel.istitle())
